name: Docker Image CI

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build the Docker image (Tag)
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker build --no-cache -t quay.io/krkn-chaos/krkn-ai -f containers/Containerfile . --build-arg VERSION=${GITHUB_REF#refs/tags/}
        docker tag quay.io/krkn-chaos/krkn-ai quay.io/redhat-chaos/krkn-ai
        docker tag quay.io/krkn-chaos/krkn-ai quay.io/krkn-chaos/krkn-ai:${GITHUB_REF#refs/tags/}
        docker tag quay.io/krkn-chaos/krkn-ai quay.io/redhat-chaos/krkn-ai:${GITHUB_REF#refs/tags/}

    - name: Test Build the Docker image (PR)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        docker build --no-cache -t quay.io/krkn-chaos/krkn-ai -f containers/Containerfile . --build-arg VERSION=${{ github.event.pull_request.number }}

    - name: Login to Quay
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USERNAME }}
        QUAY_TOKEN: ${{ secrets.QUAY_PASSWORD }}

    - name: Push the Krkn-AI Docker image
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker push quay.io/krkn-chaos/krkn-ai
        docker push quay.io/krkn-chaos/krkn-ai:${GITHUB_REF#refs/tags/}

    - name: Login to redhat-chaos Quay
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.REDHAT_QUAY_USERNAME }}
        QUAY_TOKEN: ${{ secrets.REDHAT_QUAY_PASSWORD }}

    - name: Push to redhat-chaos Quay
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker push quay.io/redhat-chaos/krkn-ai
        docker push quay.io/redhat-chaos/krkn-ai:${GITHUB_REF#refs/tags/}
